### ISSUE TITLE
Does closure inspection belong here?

### ISSUE THREAD

**Issue by aartaka** [Shinmera/trivial-arguments#13]
Closures are kind of like implied arguments and useful metadata, but I already see how this small library overgrows its name...

**Comment by Shinmera** [comment]
what do you mean by this

**Comment by aartaka** [comment]
`function-lambda-expression` returns "closure-p" as a second argument. On most implementations this "closure-p" is either a boolean or an opaque structure that's hard to deal with. I want to contribute code that parses these structures and turns them into nice symbol+value alists. Does this kind of functionality belong here?

**Comment by Shinmera** [comment]
Yeah I think that should belong in your inspector library if anything?

**Comment by aartaka** [comment]
Alright, fair. I am leaning to that too. Thanks!
