### ISSUE TITLE
Any plans to add additional trivial functions?

### ISSUE THREAD

**Issue by AlbertoEAF** [Shinmera/trivial-arguments#5]
Hello @Shinmera , first of all I'd like to say amazing library! :D

So easy to use! I just used it to add some magic to my scripts :)
With `#'arglist` alone one can do everything.

Would you consider adding more basic methods to do trivial operations such as counting the number of mandatory arguments? Or does it fall outside of the scope?

Don't know how to best name that but I had to write it for my case:
```
(defun get-function-mandatory-arguments-count (fn)
  "Returns the number of mandatory arguments in the function."
  (let ((function-arguments (arg:arglist fn))
        (special-args '(&optional &key &rest)))
    (loop for i below (length function-arguments)
       until (find (elt function-arguments i) special-args)
       finally (return i))))
```
Of course, if arglist returns :undefined, it will error out.

Also things like arg:has-&key , arg:get-&key, or arg:get-&optional/&key/&rest would be interesting to parse the arglist.

**Comment by Shinmera** [comment]
There are other libraries to do this kind of thing already and it is not within the scope of a portability library to handle this.

**Comment by AlbertoEAF** [comment]
Thank you! :)
