### ISSUE TITLE
sbcl - Incorrect arglist returned on low debug levels

### ISSUE THREAD

**Issue by Zulu-Inuoe** [Shinmera/trivial-arguments#7]
On SBCL 2.0.9:

```lisp
(trivial-arguments:arglist (locally (declare (optimize (debug 0)))
                             (lambda (x y z) (+ x y z))))
```
returns `nil`, whereas upping `debug`:
```lisp
(trivial-arguments:arglist (locally (declare (optimize (debug 3)))
                             (lambda (x y z) (+ x y z))))
```
gives me the expected result of `(x y z)`

I would instead expect `:unknown`, in order to detect that the lambda list couldn't be determined

**Comment by phoe** [comment]
I asked on `#sbcl` whether there is a way to tell whether the value returned by `sb-introspect:function-lambda-list` is `NIL` because the information was not saved from the situation where the lambda list is an empty list.

**Comment by Shinmera** [comment]
I don't believe SBCL gives us any way to distinguish the two.

**Comment by phoe** [comment]
Submitted upstream to https://bugs.launchpad.net/sbcl/+bug/1901781

**Comment by snuglas** [comment]
You may want to add your thoughts to [https://groups.google.com/g/sbcl-devel/c/bCqU3TYyqxo/m/0YWwfkyoBQAJ](url) which has attracted some criticism.
I think I'll make sb-introspect return NIL for :UNKNOWN, but suggest to you that sb-kernel:%fun-lambda-list be used to detect the actual unknown case. The issue was internally we could not detect unknown, and now we can.

**Comment by Zulu-Inuoe** [comment]
@snuglas  you may want to hold on that, as that change has been reverted partially and is still pending impl details.

Regardless you likely want to wait until the new SBCL version is officially out

**Comment by stassats** [comment]
I made it return two values, as using the internal sb-kernel:%fun-lambda-list is not a great idea.

**Comment by Zulu-Inuoe** [comment]
Oh oops. I misread what you suggested. I thought you'd be updating `trivial-arguments` to return nil rather than `:unknown`. Disregard
