### ISSUE TITLE
Do function types belong here?

### ISSUE THREAD

**Issue by aartaka** [Shinmera/trivial-arguments#9]
Hi! I have a bit of portable code for ftype fetching. Given that ftype provides argument information of an almost equal importance (at least on strongly typed implementation) to the argument names themselves, does it belong to this library? One problem is that ftype also includes return type, but it can easily be excluded from the code if you want.

**Comment by Shinmera** [comment]
I don't see a problem with including an ftype fetcher, including rettype.
